image:
  broker:
    repository: datastax/lunastreaming-all
    pullPolicy: IfNotPresent
    tag: 2.10_4.0
  brokerSts:
    repository: datastax/lunastreaming-all
    pullPolicy: IfNotPresent
    tag: 2.10_4.0
  function:
    repository: datastax/lunastreaming-all
    pullPolicy: IfNotPresent
    tag: 2.10_4.0
  zookeeper:
    repository: datastax/lunastreaming-all
    pullPolicy: IfNotPresent
    tag: 2.10_4.0
  bookkeeper:
    repository: datastax/lunastreaming-all
    pullPolicy: IfNotPresent
    tag: 2.10_4.0
  proxy:
    repository: datastax/lunastreaming-all
    pullPolicy: IfNotPresent
    tag: 2.10_4.0
  bastion:
    repository: datastax/lunastreaming-all
    pullPolicy: IfNotPresent
    tag: 2.10_4.0

enableAntiAffinity: false
enableTls: false
enableTokenAuth: false
restartOnConfigMapChange:
  enabled: true
extra:
  broker: true
  brokerSts: false
  function: true
  burnell: false
  burnellLogCollector: false
  pulsarHeartbeat: false
  pulsarAdminConsole: false

cert-manager:
  enabled: true

createCertificates:
  selfSigned:
    enabled: true

######
## default storage setting examples
## ==============================================
### Azure storage class doc (https://learn.microsoft.com/en-us/azure/aks/concepts-storage#storage-classes)
# default_storage:
#   existingStorageClassName: managed-csi-premium
##  --------------------------------------
## NOTE:
##    Somehow the following setting won't work. StandardSSD is still provisioned;
##    Use the above setting!
##  --------------------------------------
##   provisioner: kubernetes.io/azure-disk
##   fsType: ext4
##   type: managed-premium
##   extraParams:
##     storageaccounttype: Premium_LRS
##     kind: Managed
##     cachingmode: ReadOnly


zookeeper:
  replicaCount: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 0.5
  configData:
    PULSAR_MEM: "-Xms512m -Xmx512m -Djute.maxbuffer=10485760 -XX:+ExitOnOutOfMemoryError"
  # volumes:
  #   data:
  #     name: data
  #     size: 1Gi

bookkeeper:
  replicaCount: 1
  resources:
    requests:
      memory: 1024Mi
      cpu: 0.5
  # volumes:
  #   journal:
  #     name: journal
  #     size: 1Gi
  #   ledgers:
  #     name: ledgers
  #     size: 2Gi
  configData:
    BOOKIE_MEM: "-Xms800m -Xmx800m -XX:MaxDirectMemorySize=224m -XX:+ExitOnOutOfMemoryError"

broker:
  component: broker
  replicaCount: 1
  service:
    type: ClusterIP
    headless: false
    ports:
      - name: http
        port: 8080
      - name: pulsar
        port: 6650
      - name: https
        port: 8443
      - name: pulsarssl
        port: 6651
  ledger:
    defaultEnsembleSize: 1
    defaultAckQuorum: 1
    defaultWriteQuorum: 1
  resources:
    requests:
      memory: 1024Mi
      cpu: 1.0
  configData:
    PULSAR_MEM: "-Xms800m -Xmx800m -XX:MaxDirectMemorySize=224m -XX:+ExitOnOutOfMemoryError"
    PULSAR_PREFIX_allowAutoTopicCreationType: "partitioned"
    PULSAR_PREFIX_brokerDeleteInactiveTopicsEnabled: "false"

autoRecovery:
  enableProvisionContainer: true
  resources:
    requests:
      memory: 500Mi
      cpu: 0.5

function:
  replicaCount: 1
  functionReplicaCount: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 0.5
  # volumes:
  #   data:
  #     name: logs
  #     size: 1Gi
  configData:
    PULSAR_MEM: "-Xms400m -Xmx400m -XX:MaxDirectMemorySize=112m -XX:+ExitOnOutOfMemoryError"
    PULSAR_EXTRA_OPTS: "-Dpulsar.log.root.level=trace"

proxy:
  replicaCount: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 0.5
  wsResources:
    requests:
      memory: 512Mi
      cpu: 0.5
  configData:
    PULSAR_MEM: "-Xms400m -Xmx400m -XX:MaxDirectMemorySize=112m"
    PULSAR_PREFIX_saslAllowedMechanisms: PLAIN
  autoPortAssign:
    enablePlainTextWithTLS: true
  service:
    autoPortAssign:
      enabled: true

pulsarAdminConsole:
  replicaCount: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 0.5

grafanaDashboards:
  enabled: true

kube-prometheus-stack:
  enabled: true
  prometheusOperator:
    enabled: false
  nodeExporter:
    enabled: false
  grafana:
    enabled: true
    adminPassword: e9JYtk83*4#PM8